//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flee.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompileErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompileErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flee.Resources.CompileErrors", typeof(CompileErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous call of function &apos;{0}({1})&apos;.
        /// </summary>
        internal static string AmbiguousCallOfFunction {
            get {
                return ResourceManager.GetString("AmbiguousCallOfFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous overloaded operator (&apos;{2}&apos;) in types &apos;{0}&apos; and &apos;{1}&apos;.
        /// </summary>
        internal static string AmbiguousOverloadedOperator {
            get {
                return ResourceManager.GetString("AmbiguousOverloadedOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis: {0}.
        /// </summary>
        internal static string ANALYSIS {
            get {
                return ResourceManager.GetString("ANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array indexers must be of type &apos;{0}&apos;.
        /// </summary>
        internal static string ArrayIndexersMustBeOfType {
            get {
                return ResourceManager.GetString("ArrayIndexersMustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calculation engine does not contain the atom &apos;${0}&apos;.
        /// </summary>
        internal static string CalcEngineDoesNotContainAtom {
            get {
                return ResourceManager.GetString("CalcEngineDoesNotContainAtom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert type &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        internal static string CannotConvertType {
            get {
                return ResourceManager.GetString("CannotConvertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert type &apos;{0}&apos; to expression result of &apos;{1}&apos;.
        /// </summary>
        internal static string CannotConvertTypeToExpressionResult {
            get {
                return ResourceManager.GetString("CannotConvertTypeToExpressionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String was not recognized as a valid &apos;{0}&apos;.
        /// </summary>
        internal static string CannotParseType {
            get {
                return ResourceManager.GetString("CannotParseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reference a calculation engine atom without a calculation engine.
        /// </summary>
        internal static string CannotReferenceCalcEngineAtomWithoutCalcEngine {
            get {
                return ResourceManager.GetString("CannotReferenceCalcEngineAtomWithoutCalcEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve type of &apos;{0}&apos;.
        /// </summary>
        internal static string CouldNotResolveType {
            get {
                return ResourceManager.GetString("CouldNotResolveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First argument does not evaluate to a Boolean.
        /// </summary>
        internal static string FirstArgNotBoolean {
            get {
                return ResourceManager.GetString("FirstArgNotBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; does not return a value.
        /// </summary>
        internal static string FunctionHasNoReturnValue {
            get {
                return ResourceManager.GetString("FunctionHasNoReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field/property/variable name &apos;{0}&apos; is ambiguous.
        /// </summary>
        internal static string IdentifierIsAmbiguous {
            get {
                return ResourceManager.GetString("IdentifierIsAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field/property/variable name &apos;{0}&apos; is ambiguous on type &apos;{1}&apos;.
        /// </summary>
        internal static string IdentifierIsAmbiguousOnType {
            get {
                return ResourceManager.GetString("IdentifierIsAmbiguousOnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: {0}.
        /// </summary>
        internal static string INTERNAL_ERROR {
            get {
                return ResourceManager.GetString("INTERNAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Token: {0}.
        /// </summary>
        internal static string INVALID_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O error: {0}.
        /// </summary>
        internal static string IO {
            get {
                return ResourceManager.GetString("IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line: {0}, Column: {1}.
        /// </summary>
        internal static string LineColumn {
            get {
                return ResourceManager.GetString("LineColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple array indexes are not supported.
        /// </summary>
        internal static string MultiArrayIndexNotSupported {
            get {
                return ResourceManager.GetString("MultiArrayIndexNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace &apos;{0}&apos; cannot be used as a type.
        /// </summary>
        internal static string NamespaceCannotBeUsedAsType {
            get {
                return ResourceManager.GetString("NamespaceCannotBeUsedAsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine result type of expression; neither the True ({0}) or False ({1}) arguments are convertible to one another.
        /// </summary>
        internal static string NeitherArgIsConvertibleToTheOther {
            get {
                return ResourceManager.GetString("NeitherArgIsConvertibleToTheOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any accessible matches for &apos;{0}({1})&apos;.
        /// </summary>
        internal static string NoAccessibleMatches {
            get {
                return ResourceManager.GetString("NoAccessibleMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any accessible matches for &apos;{0}({1})&apos; on type &apos;{2}&apos;.
        /// </summary>
        internal static string NoAccessibleMatchesOnType {
            get {
                return ResourceManager.GetString("NoAccessibleMatchesOnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a field/property/variable with the name &apos;{0}&apos;.
        /// </summary>
        internal static string NoIdentifierWithName {
            get {
                return ResourceManager.GetString("NoIdentifierWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a field/property/variable with the name &apos;{0}&apos; on the type &apos;{1}&apos;.
        /// </summary>
        internal static string NoIdentifierWithNameOnType {
            get {
                return ResourceManager.GetString("NoIdentifierWithNameOnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operand type of &apos;{0}&apos; is not convertible to collection type of &apos;{1}&apos;.
        /// </summary>
        internal static string OperandNotConvertibleToCollectionType {
            get {
                return ResourceManager.GetString("OperandNotConvertibleToCollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not defined for type &apos;{0}&apos;.
        /// </summary>
        internal static string OperationNotDefinedForType {
            get {
                return ResourceManager.GetString("OperationNotDefinedForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation &apos;{0}&apos; is not defined for types &apos;{1}&apos; and &apos;{2}&apos;.
        /// </summary>
        internal static string OperationNotDefinedForTypes {
            get {
                return ResourceManager.GetString("OperationNotDefinedForTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to a non-shared member &apos;{0}&apos; requires an object reference.
        /// </summary>
        internal static string ReferenceToNonSharedMemberRequiresObjectReference {
            get {
                return ResourceManager.GetString("ReferenceToNonSharedMemberRequiresObjectReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search argument type &apos;{0}&apos; is not a known collection type.
        /// </summary>
        internal static string SearchArgIsNotKnownCollectionType {
            get {
                return ResourceManager.GetString("SearchArgIsNotKnownCollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static member &apos;{0}&apos; cannot be accessed with an instance reference; qualify it with a type name instead.
        /// </summary>
        internal static string StaticMemberCannotBeAccessedWithInstanceReference {
            get {
                return ResourceManager.GetString("StaticMemberCannotBeAccessedWithInstanceReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyntaxError.
        /// </summary>
        internal static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a type and cannot be used as an expression.
        /// </summary>
        internal static string TypeCannotBeUsedAsAnExpression {
            get {
                return ResourceManager.GetString("TypeCannotBeUsedAsAnExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not an array and does not have an indexer which accepts &apos;{1}&apos;.
        /// </summary>
        internal static string TypeNotArrayAndHasNoIndexerOfType {
            get {
                return ResourceManager.GetString("TypeNotArrayAndHasNoIndexerOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could find not function &apos;{0}({1})&apos;.
        /// </summary>
        internal static string UndefinedFunction {
            get {
                return ResourceManager.GetString("UndefinedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could find not function &apos;{0}({1})&apos; on type &apos;{2}&apos;.
        /// </summary>
        internal static string UndefinedFunctionOnType {
            get {
                return ResourceManager.GetString("UndefinedFunctionOnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character: {0}.
        /// </summary>
        internal static string UNEXPECTED_CHAR {
            get {
                return ResourceManager.GetString("UNEXPECTED_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file.
        /// </summary>
        internal static string UNEXPECTED_EOF {
            get {
                return ResourceManager.GetString("UNEXPECTED_EOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token {0}; expected one of {1}.
        /// </summary>
        internal static string UNEXPECTED_TOKEN {
            get {
                return ResourceManager.GetString("UNEXPECTED_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; not representable in type &apos;{1}&apos;.
        /// </summary>
        internal static string ValueNotRepresentableInType {
            get {
                return ResourceManager.GetString("ValueNotRepresentableInType", resourceCulture);
            }
        }
    }
}
